version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - sockets:/tmp/sockets
      - alexdb-storage:/tmp
    environment:
      UDP_PORT: 3001
      ALEXDB_UDP_PORT: 3000
    ports:
      - 3001:3001/udp
      - 3002:3002/udp
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      PRIMARY: 1
      UDP_PORT: 3002
      ALEXDB_UDP_PORT: 3000

  db:
    build: ../alexdb
    user: www-data:www-data
    environment:
      DATA_PATH: /tmp
      UDP_PORT: 3000
    ports:
      - 3000:3000/udp
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "50MB"
    volumes:
      - sockets:/tmp/sockets
      - alexdb-storage:/tmp
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

volumes:
  sockets:
  alexdb-storage:
