version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DB_HOST=db
      - PORT=80
    expose:
      - "80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgres.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1